---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eugene-food-scene-stage-mapping
  namespace: ambassador-edge
spec:
  host: eugenefoodscene.stage.apps.mvpstudio.org
  prefix: /
  service: eugene-food-scene-web.eugene-food-scene-stage
  use_websocket: true
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: eugene-food-scene-stage-host
  namespace: ambassador-edge
spec:
  hostname: eugenefoodscene.stage.apps.mvpstudio.org
  acmeProvider:
    email: mvpstudiooregon@gmail.com
